"use client";
import{useEffect,useMemo,useRef,useState}from"react";import{MessageSquare,Phone}from"lucide-react";import{BookingQuizShell}from"./BookingQuizShell";import{BookingQuizNavigation}from"./BookingQuizNavigation";import{BookingQuizSuccess}from"./BookingQuizSuccess";import{clearQuiz,readQuiz,saveQuiz}from"@/lib/bookingQuizStorage";import{getMinimumEventDate}from"@/lib/bookingValidation";import{createSmsLink,phoneLink}from"@/lib/contactLinks";import styles from"./BookingQuiz.module.css";
type Answers={eventDate:string;dateStatus:"known"|"unknown";eventType:string;customEventType:string;guestRange:string;zone:string;locationReference:string;cocktails:string[];needs:string[];supplyQuestions:string[];customSupplyQuestion:string;name:string;phone:string;email:string;message:string};
const empty:Answers={eventDate:"",dateStatus:"known",eventType:"",customEventType:"",guestRange:"",zone:"",locationReference:"",cocktails:[],needs:[],supplyQuestions:[],customSupplyQuestion:"",name:"",phone:"",email:"",message:""};
const events=["Cumpleaños","Boda","Reunión privada","Graduación","Otra celebración social"],guests=["Menos de 20","20–40","41–70","71–100","Más de 100","Aún no lo sé"],cocktails=["Piña Colada","Mojito","Margarita","Cuba Libre","Sex on the Beach","Screwdriver","Daiquiri","Old Fashioned","PepoShots, especial de la casa","Aún no estoy seguro"],needs=["Servicio de bartender","Servicio para invitados","Ayuda para elegir los cócteles","Organización general del bar","Aún no estoy seguro"],supplies=["Alcohol","Mezcladores y jugos","Frutas y decoraciones","Hielo","Vasos y servilletas","Barra o mesa","Montaje","Otro detalle","No tengo dudas por ahora"];
const toggle=(list:string[],value:string)=>list.includes(value)?list.filter(x=>x!==value):[...list,value];
export function BookingQuiz({open,startStep,onClose}:{open:boolean;startStep:number|null;onClose:()=>void}){
 const[step,setStep]=useState(0),[data,setData]=useState(empty),[loading,setLoading]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState<string|null>(null);const root=useRef<HTMLDivElement>(null);
 const flow=useMemo(()=>startStep===null?[0,1,2,3,4,5,6,7,8]:[startStep,...[0,1,2,3,4,5,6,7,8].filter(item=>item!==startStep)],[startStep]);
 const flowIndex=Math.max(0,flow.indexOf(step));
 useEffect(()=>{if(!open)return;const saved=readQuiz<{step:number;answers:Answers}|null>(null);if(saved){setStep(saved.step);setData({...empty,...saved.answers})}const old=document.body.style.overflow;document.body.style.overflow="hidden";setTimeout(()=>root.current?.querySelector<HTMLElement>("button,input")?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"&&root.current){const f=Array.from(root.current.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea'));if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key)}},[open,onClose]);
 useEffect(()=>{if(!open||startStep===null)return;setStep(startStep);try{const selected=JSON.parse(sessionStorage.getItem("peposhots-selected-cocktails")||"[]");if(Array.isArray(selected)){const names=selected.map((item:any)=>typeof item==="string"?item:item?.name).filter(Boolean);setData(current=>({...current,cocktails:Array.from(new Set([...current.cocktails,...names]))}))}}catch{}},[open,startStep]);
 useEffect(()=>{if(open&&!success)saveQuiz({step,answers:data,updatedAt:new Date().toISOString()})},[open,step,data,success]);
 const valid=useMemo(()=>{switch(step){case 0:return data.dateStatus==="unknown"||!!data.eventDate&&data.eventDate>=getMinimumEventDate();case 1:return!!data.eventType&&(data.eventType!=="Otra celebración social"||!!data.customEventType.trim());case 2:return!!data.guestRange;case 3:return!!data.zone.trim();case 4:return data.cocktails.length>0;case 5:return data.needs.length>0;case 6:return data.supplyQuestions.length>0&&( !data.supplyQuestions.includes("Otro detalle")||!!data.customSupplyQuestion.trim());case 7:return data.name.trim().length>=2&&(data.phone.match(/\d/g)||[]).length>=7&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email);default:return true}},[step,data]);
 const set=(key:keyof Answers,value:any)=>{setError("");setData(x=>({...x,[key]:value}))};
 async function next(){if(!valid){setError("Completa esta respuesta para continuar.");return}if(flowIndex<flow.length-1){setStep(flow[flowIndex+1]);return}setLoading(true);setError("");try{const payload={...data,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:"inquiry"};const details=[data.message,data.cocktails.length?`Cócteles: ${data.cocktails.join(", ")}`:"",data.needs.length?`Necesidades: ${data.needs.join(", ")}`:"",data.supplyQuestions.length?`Dudas sobre suministros: ${data.supplyQuestions.join(", ")}`:"",data.customSupplyQuestion?`Otro detalle: ${data.customSupplyQuestion}`:"",data.locationReference?`Venue o referencia: ${data.locationReference}`:""].filter(Boolean).join("\n");const response=await fetch("/api/lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.name,phone:data.phone,email:data.email,eventDate:data.eventDate||"Fecha por definir",eventType:data.customEventType||data.eventType,location:data.zone,guestCount:data.guestRange,message:details,company:""})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||"No pudimos enviar tu consulta.");clearQuiz();setSuccess(payload.id)}catch(error){setError(error instanceof Error?error.message:"No pudimos enviar tu consulta. Puedes hablar por texto o llamar directamente.")}finally{setLoading(false)}}
 function restart(){if((step>0||Object.values(data).some(v=>Array.isArray(v)?v.length:Boolean(v)))&&!confirm("¿Quieres descartar esta consulta y empezar de nuevo?"))return;clearQuiz();setData(empty);setStep(0);setSuccess(null);setError("")}
 if(!open)return null;
 const option=(value:string,selected:boolean,onClick:()=>void)=><button key={value} className={`${styles.option} ${selected?styles.selected:""}`} type="button" onClick={onClick} aria-pressed={selected}>{value}</button>;
 let body=<></>;if(step===0)body=<div className={styles.question}><h2>¿Cuándo será tu evento?</h2><p>Necesitamos al menos dos semanas para organizar el servicio.</p><label className={styles.field}>Fecha del evento<input className={styles.input} type="date" min={getMinimumEventDate()} value={data.eventDate} disabled={data.dateStatus==="unknown"} onChange={e=>set("eventDate",e.target.value)}/></label><label className={styles.check}><input type="checkbox" checked={data.dateStatus==="unknown"} onChange={e=>setData(x=>({...x,dateStatus:e.target.checked?"unknown":"known",eventDate:e.target.checked?"":x.eventDate}))}/>Aún no tengo la fecha exacta</label></div>;
 if(step===1)body=<div className={styles.question}><h2>¿Qué estás celebrando?</h2><div className={styles.options}>{events.map(x=>option(x,data.eventType===x,()=>set("eventType",x)))}</div>{data.eventType==="Otra celebración social"&&<label className={styles.field}>Cuéntanos qué tipo de celebración es<input className={styles.input} value={data.customEventType} onChange={e=>set("customEventType",e.target.value)}/></label>}</div>;
 if(step===2)body=<div className={styles.question}><h2>¿Cuántas personas esperas?</h2><div className={styles.options}>{guests.map(x=>option(x,data.guestRange===x,()=>set("guestRange",x)))}</div></div>;
 if(step===3)body=<div className={styles.question}><h2>¿En qué zona de Miami será?</h2><label className={styles.field}>Ciudad, vecindario o zona aproximada<input className={styles.input} placeholder="Ciudad, vecindario o zona aproximada" value={data.zone} onChange={e=>set("zone",e.target.value)}/></label><p>PepoShots ofrece servicio en Miami. Confirmaremos la cobertura exacta según la ubicación.</p><label className={styles.field}>Venue o referencia (opcional)<input className={styles.input} value={data.locationReference} onChange={e=>set("locationReference",e.target.value)}/></label></div>;
 if(step===4)body=<div className={styles.question}><h2>¿Qué cócteles te gustaría ofrecer?</h2><p>Puedes elegir varios o dejar que PepoShots te oriente.</p><div className={styles.options}>{cocktails.map(x=>option(x,data.cocktails.includes(x),()=>set("cocktails",toggle(data.cocktails,x))))}</div></div>;
 if(step===5)body=<div className={styles.question}><h2>¿Qué necesitas para tu evento?</h2><div className={styles.options}>{needs.map(x=>option(x,data.needs.includes(x),()=>set("needs",toggle(data.needs,x))))}</div></div>;
 if(step===6)body=<div className={styles.question}><h2>¿Qué te gustaría confirmar con PepoShots?</h2><p>Los detalles pueden cambiar según cada evento.</p><div className={styles.options}>{supplies.map(x=>option(x,data.supplyQuestions.includes(x),()=>set("supplyQuestions",toggle(data.supplyQuestions,x))))}</div>{data.supplyQuestions.includes("Otro detalle")&&<label className={styles.field}>Otro detalle<input className={styles.input} value={data.customSupplyQuestion} onChange={e=>set("customSupplyQuestion",e.target.value)}/></label>}</div>;
 if(step===7)body=<div className={styles.question}><h2>¿Cómo podemos contactarte?</h2><label className={styles.field}>Nombre<input className={styles.input} value={data.name} placeholder="¿Cómo te llamas?" onChange={e=>set("name",e.target.value)} aria-invalid={data.name.length>0&&data.name.trim().length<2}/>{data.name.length>0&&data.name.trim().length<2&&<span className={styles.error}>Escribe al menos 2 caracteres.</span>}</label><label className={styles.field}>Teléfono<input className={styles.input} type="tel" value={data.phone} placeholder="(305) 000-0000" onChange={e=>set("phone",e.target.value)} aria-invalid={data.phone.length>0&&(data.phone.match(/\d/g)||[]).length<7}/>{data.phone.length>0&&(data.phone.match(/\d/g)||[]).length<7&&<span className={styles.error}>Escribe un teléfono con al menos 7 dígitos.</span>}</label><label className={styles.field}>Email<input className={styles.input} type="email" value={data.email} placeholder="tu@email.com" onChange={e=>set("email",e.target.value)} aria-invalid={data.email.length>0&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)}/>{data.email.length>0&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)&&<span className={styles.error}>Incluye un email válido, por ejemplo nombre@gmail.com.</span>}</label><p>¿Prefieres hablar directamente?</p><div className={styles.contactLinks}><a href={createSmsLink(data)}><MessageSquare size={16}/>Hablar por texto</a><a href={phoneLink}><Phone size={16}/>Llamar ahora</a></div></div>;
 if(step===8)body=<div className={styles.question}><h2>¿Hay algo más que debamos saber?</h2><label className={styles.field}>Detalles finales<textarea className={styles.input} maxLength={600} placeholder="Tema, estilo, bebidas favoritas o cualquier detalle importante." value={data.message} onChange={e=>set("message",e.target.value)}/><span className={styles.counter}>{data.message.length}/600</span></label><div className={styles.summary}><span><b>Fecha:</b> {data.dateStatus==="unknown"?"Por definir":data.eventDate}</span><span><b>Evento:</b> {data.customEventType||data.eventType}</span><span><b>Invitados:</b> {data.guestRange}</span><span><b>Zona:</b> {data.zone}</span><span><b>Cócteles:</b> {data.cocktails.join(", ")}</span><span><b>Necesidades:</b> {data.needs.join(", ")}</span></div></div>;
 return <div ref={root}>{success?<div className={styles.overlay}><section className={styles.shell} role="dialog" aria-modal="true"><main className={styles.content}><BookingQuizSuccess data={data} id={success} onClose={onClose} onReset={restart}/></main></section></div>:<BookingQuizShell step={flowIndex} total={9} onClose={onClose} navigation={<BookingQuizNavigation step={flowIndex} total={9} valid={valid} loading={loading} onBack={()=>setStep(flow[flowIndex-1])} onNext={next}/>}>{body}{error&&<p className={styles.error} role="alert">{error}</p>}</BookingQuizShell>}</div>
}
